name: Build OcrHelper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Force update repository
      run: |
        git clone https://github.com/xksoft/OcrHelper.git
        cd OcrHelper

    - name: Restore NuGet packages
      run: |
        cd OcrHelper
        nuget restore OcrHelper.sln
      
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: |
        cd OcrHelper
        msbuild OcrHelper.sln /p:Configuration=Release

    - name: Compress Output Directory
      run: |
        cd OcrHelper/bin
        Compress-Archive -Path bin\Release -DestinationPath OcrHelper-output.zip

    - name: Archive Output
      uses: actions/upload-artifact@v3
      with:
        name: OcrHelper-output
        path: OcrHelper/bin/OcrHelper-output.zip
