name: Build OcrHelper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Force update repository
      run: |
        git clone https://github.com/xksoft/OcrHelper.git
        cd D:\a\csharp-actions\csharp-actions\OcrHelper
        cd
    - name: Restore NuGet packages
      run: nuget restore D:\a\csharp-actions\csharp-actions\OcrHelper\OcrHelper.sln
      
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build Solution
      run: msbuild D:\a\csharp-actions\csharp-actions\OcrHelper\OcrHelper.sln /p:Configuration=Release

    - name: Archive Output
      uses: actions/upload-artifact@v3
      with:
        name: OcrHelper-output
        path: |
          **/Release/*.exe
